{
  "errorMessage": "An HTTP Client raised an unhandled exception: Not supported URL scheme wss",
  "errorType": "HTTPClientError",
  "requestId": "2dfbc338-e470-498b-8fd2-cf96735f44e2",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 101, in lambda_handler\n    apigw.post_to_connection(\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/client.py\", line 602, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/context.py\", line 123, in wrapper\n    return func(*args, **kwargs)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/client.py\", line 1060, in _make_api_call\n    http, parsed_response = self._make_request(\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/client.py\", line 1084, in _make_request\n    return self._endpoint.make_request(operation_model, request_dict)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/endpoint.py\", line 119, in make_request\n    return self._send_request(request_dict, operation_model)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/endpoint.py\", line 200, in _send_request\n    while self._needs_retry(\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/endpoint.py\", line 360, in _needs_retry\n    responses = self._event_emitter.emit(\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/hooks.py\", line 412, in emit\n    return self._emitter.emit(aliased_event_name, **kwargs)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/hooks.py\", line 256, in emit\n    return self._emit(event_name, kwargs)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/hooks.py\", line 239, in _emit\n    response = handler(**kwargs)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/retryhandler.py\", line 207, in __call__\n    if self._checker(**checker_kwargs):\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/retryhandler.py\", line 284, in __call__\n    should_retry = self._should_retry(\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/retryhandler.py\", line 307, in _should_retry\n    return self._checker(\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/retryhandler.py\", line 363, in __call__\n    checker_response = checker(\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/retryhandler.py\", line 247, in __call__\n    return self._check_caught_exception(\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/retryhandler.py\", line 416, in _check_caught_exception\n    raise caught_exception\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/endpoint.py\", line 279, in _do_get_response\n    http_response = self._send(request)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/endpoint.py\", line 383, in _send\n    return self.http_session.send(request)\n",
    "  File \"/var/lang/lib/python3.11/site-packages/botocore/httpsession.py\", line 509, in send\n    raise HTTPClientError(error=e)\n"
  ]
}
